name: Deploy next 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server (as ubuntu)
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 3.109.49.243
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            set -euo pipefail
            echo "Starting deploy as LexHouse on $(hostname) ..."

            # App path
            cd /var/www/html/GitHub-actions-CICD-EC2/ || { echo "path not found"; exit 1; }


            git pull origin main
            npm install
            npm run build

            pm2 reload 0
            echo "Deploy finished."
